/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        error: '#ba1a1a',
        'secondary-container': '#fd8c68',
        'tertiary-container': '#1b293b',
        'on-surface': '#191c1e',
        'on-error': '#ffffff',
        'surface-container-highest': '#e0e3e5',
        primary: '#091426',
        'on-error-container': '#93000a',
        'tertiary-fixed': '#d5e3fc',
        'on-primary-fixed-variant': '#3c475a',
        'on-tertiary-fixed-variant': '#3a485b',
        'on-primary': '#ffffff',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#742508',
        secondary: '#9d4225',
        'on-tertiary-fixed': '#0d1c2e',
        'surface-dim': '#d8dadc',
        'surface-bright': '#f7f9fb',
        'secondary-fixed': '#ffdbd0',
        'inverse-primary': '#bcc7de',
        'secondary-fixed-dim': '#ffb59e',
        'primary-fixed-dim': '#bcc7de',
        background: '#f7f9fb',
        'on-surface-variant': '#45474c',
        'surface-container-lowest': '#ffffff',
        'surface-container': '#eceef0',
        'primary-fixed': '#d8e3fb',
        'surface-container-high': '#e6e8ea',
        'surface-container-low': '#f2f4f6',
        'inverse-on-surface': '#eff1f3',
        'on-primary-container': '#8590a6',
        'tertiary-fixed-dim': '#b9c7df',
        'error-container': '#ffdad6',
        'primary-container': '#1e293b',
        'on-tertiary': '#ffffff',
        'on-secondary-fixed-variant': '#7e2c10',
        'on-tertiary-container': '#8290a6',
        surface: '#f7f9fb',
        'surface-tint': '#545f73',
        'on-secondary-fixed': '#3a0b00',
        'outline-variant': '#c5c6cd',
        tertiary: '#051426',
        'surface-variant': '#e0e3e5',
        'on-primary-fixed': '#111c2d',
        outline: '#75777d',
        'on-background': '#191c1e',
        'inverse-surface': '#2d3133',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        margin: '2rem',
        gutter: '1.5rem',
        'space-sm': '0.5rem',
        'space-xl': '2.5rem',
        'space-xs': '0.25rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
      },
      fontFamily: {
        'display-lg': ['"Source Serif 4"'],
        'label-md': ['Inter'],
        'body-sm': ['Inter'],
        'body-lg': ['"Source Serif 4"'],
        'headline-sm': ['"Source Serif 4"'],
        'label-sm': ['Inter'],
        'title-md': ['Inter'],
        'body-md': ['Inter'],
        'headline-lg': ['"Source Serif 4"'],
        'headline-md': ['"Source Serif 4"'],
        serif: ['"Source Serif 4"', 'serif'],
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['2.75rem', { lineHeight: '3.25rem', letterSpacing: '-0.02em', fontWeight: '600' }],
        'label-md': ['0.8125rem', { lineHeight: '1.125rem', letterSpacing: '0.02em', fontWeight: '600' }],
        'body-sm': ['0.8125rem', { lineHeight: '1.25rem', letterSpacing: '0.005em', fontWeight: '400' }],
        'body-lg': ['1.125rem', { lineHeight: '1.875rem', letterSpacing: '0em', fontWeight: '400' }],
        'headline-sm': ['1.25rem', { lineHeight: '1.75rem', letterSpacing: '0em', fontWeight: '600' }],
        'label-sm': ['0.6875rem', { lineHeight: '1rem', letterSpacing: '0.04em', fontWeight: '600' }],
        'title-md': ['1rem', { lineHeight: '1.5rem', letterSpacing: '-0.005em', fontWeight: '600' }],
        'body-md': ['0.9375rem', { lineHeight: '1.5rem', letterSpacing: '0em', fontWeight: '400' }],
        'headline-lg': ['2rem', { lineHeight: '2.5rem', letterSpacing: '-0.015em', fontWeight: '600' }],
        'headline-md': ['1.5rem', { lineHeight: '2rem', letterSpacing: '-0.01em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
