/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-container-highest': '#d5dce4',
        'on-secondary': '#ffffff',
        'on-surface-variant': '#4a5568',
        'tertiary-fixed-dim': '#e5c0a1',
        'on-tertiary-fixed-variant': '#5b422a',
        secondary: '#9d4225',
        'surface-dim': '#e2e6eb',
        'on-surface': '#191c1e',
        'inverse-primary': '#bcc7df',
        surface: '#f7f9fb',
        'surface-container-high': '#e6e8ea',
        'on-error-container': '#93000a',
        'on-primary-fixed': '#111c2e',
        'on-primary-container': '#e2e8f0',
        'on-tertiary-container': '#9d7e62',
        error: '#ba1a1a',
        'primary-container': '#1a273e',
        'secondary-fixed': '#ffdbd0',
        'secondary-container': '#fe8c69',
        'surface-variant': '#e0e3e5',
        outline: '#cbd5e1',
        'on-secondary-container': '#2c0c04',
        'surface-tint': '#545f74',
        'surface-bright': '#f7f9fb',
        'inverse-on-surface': '#eff1f3',
        'on-tertiary': '#ffffff',
        'secondary-fixed-dim': '#ffb59f',
        'surface-container': '#e8ecf1',
        'primary-fixed-dim': '#bcc7df',
        background: '#f7f9fb',
        'surface-container-lowest': '#ffffff',
        'on-error': '#ffffff',
        'on-secondary-fixed': '#3a0a00',
        tertiary: '#000000',
        'inverse-surface': '#2d3133',
        'outline-variant': '#c5c6cd',
        'error-container': '#ffdad6',
        'on-primary': '#ffffff',
        'tertiary-container': '#2a1704',
        'tertiary-fixed': '#ffdcc0',
        'surface-container-low': '#f1f4f8',
        'on-background': '#191c1e',
        primary: '#000000',
        'on-primary-fixed-variant': '#3d475b',
        'on-tertiary-fixed': '#2a1704',
        'primary-fixed': '#d8e2fc',
        'on-secondary-fixed-variant': '#7e2b10',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        margin: '2rem',
        gutter: '1.5rem',
        'space-sm': '0.5rem',
        'space-xl': '2.5rem',
        'space-xs': '0.25rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
      },
      fontFamily: {
        'body-lg': ['Inter'],
        'headline-lg': ['"Source Serif 4"'],
        'label-lg': ['Inter'],
        'title-lg': ['Inter'],
        'label-sm': ['Inter'],
        'body-sm': ['Inter'],
        'display-lg': ['"Source Serif 4"'],
        'headline-md': ['"Source Serif 4"'],
        'label-md': ['Inter'],
        'headline-sm': ['"Source Serif 4"'],
        'title-md': ['Inter'],
        'body-md': ['Inter'],
        serif: ['"Source Serif 4"', 'serif'],
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'label-lg': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'title-lg': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '14px', fontWeight: '500' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '56px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'title-md': ['16px', { lineHeight: '22px', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
